"""Weekly retrospective (I4).

Sent Sunday 18:00. Pure data, no guilt:
- Week-over-week trend summary: HRV, RHR, sleep, readiness
- Action completion totals (only positive)
- Top 3 action effects (what moved metrics)
- One insight line generated by Gemini

Emailed via existing send_advice_email with a slim retrospective payload.
"""
from __future__ import annotations

import logging
from datetime import date, datetime, timedelta
from typing import Any, Dict, List

from .config import SyncConfig

logger = logging.getLogger("personal-doctor.weekly_retro")


def _week_metrics(config: SyncConfig, today: date) -> Dict[str, Any]:
    from .trend_analyzer import compute_rolling_averages, load_primary_wearable_history

    current_week = load_primary_wearable_history(config.data_dir, today, num_days=7)
    prior_week = load_primary_wearable_history(
        config.data_dir, today - timedelta(days=7), num_days=7
    )
    cur_avg = compute_rolling_averages(current_week)
    prior_avg = compute_rolling_averages(prior_week)
    return {"current": cur_avg, "prior": prior_avg}


def _delta_bullets(week_metrics: Dict[str, Any]) -> List[str]:
    labels = {
        "avg_hrv": ("HRV", "ms", True),
        "avg_resting_hr": ("Resting HR", "bpm", False),  # lower is better
        "avg_sleep_hours": ("Sleep", "h", True),
        "avg_deep_sleep_min": ("Deep sleep", "min", True),
        "avg_readiness": ("Readiness", "/100", True),
    }
    cur = week_metrics.get("current", {})
    prior = week_metrics.get("prior", {})
    out = []
    for key, (label, unit, higher_is_better) in labels.items():
        c = cur.get(key)
        p = prior.get(key)
        if c is None or p is None or p == 0:
            continue
        delta = round(c - p, 1)
        pct = (c - p) / p
        if abs(pct) < 0.02:
            arrow = "→"
            direction = "stable"
        elif (pct > 0) == higher_is_better:
            arrow = "↑"
            direction = "better"
        else:
            arrow = "↓"
            direction = "worse"
        sign = "+" if delta >= 0 else ""
        out.append(f"{label}: {c:.1f} {unit} {arrow} ({sign}{delta} vs prior week — {direction})")
    return out


def _action_totals(config: SyncConfig, today: date) -> Dict[str, int]:
    from .action_tracker import load_action_history

    hist = load_action_history(config.data_dir, num_days=7)
    total = sum(len(d.get("actions", [])) for d in hist)
    done = sum(
        sum(1 for a in d.get("actions", []) if a.get("done")) for d in hist
    )
    return {"total": total, "done": done}


def _gemini_insight(config: SyncConfig, data: Dict[str, Any]) -> str:
    if not config.google_api_key:
        return ""
    try:
        from google import genai
        from google.genai import types

        client = genai.Client(api_key=config.google_api_key)
        model = config.gemini_model or "gemini-3.1-flash-lite-preview"
        prompt = (
            "Weekly retrospective data:\n"
            + str(data)
            + "\n\nIn ONE sentence, what's the most useful insight? Be concrete."
        )
        response = client.models.generate_content(
            model=model,
            contents=prompt,
            config=types.GenerateContentConfig(max_output_tokens=120),
        )
        return (response.text or "").strip().split("\n")[0]
    except Exception as exc:
        logger.warning(f"Gemini insight failed: {exc}")
        return ""


def run_weekly_retro() -> None:
    """Called by the scheduler Sunday at 18:00."""
    from .config import load_config
    from .email_sender import send_advice_email

    config = load_config()
    today = datetime.now(tz=config.timezone).date()

    metrics = _week_metrics(config, today)
    delta_lines = _delta_bullets(metrics)
    totals = _action_totals(config, today)

    effects: List[Dict[str, Any]] = []
    try:
        from .action_effects import compute_action_effects

        effects = compute_action_effects(config.data_dir, today, lookback_days=14)
    except Exception:
        effects = []

    insight = _gemini_insight(
        config,
        {
            "metric_deltas": delta_lines,
            "actions_done": totals,
            "top_effects": [
                {"a": e["action"], "m": e["metric"], "d": e["delta"]}
                for e in effects[:3]
            ],
        },
    )

    body_md = [f"## Weekly Retrospective — week ending {today.isoformat()}"]
    if insight:
        body_md.append(f"**Insight:** {insight}")
    body_md.append("")
    body_md.append("### Metrics (7-day averages vs prior week)")
    if delta_lines:
        for line in delta_lines:
            body_md.append(f"- {line}")
    else:
        body_md.append("- Not enough data for comparison.")
    body_md.append("")
    body_md.append(
        f"### Actions this week\nYou completed **{totals['done']}** "
        f"action(s) out of {totals['total']} planned."
    )
    if effects:
        body_md.append("")
        body_md.append("### What moved the needle (last 14 days)")
        for e in effects[:3]:
            arrow = "⬆" if e.get("impact", 0) > 0 else "⬇"
            body_md.append(
                f"- {arrow} **{e['action']}**: {e['metric']} {e['delta']}"
            )
    body_md.append("")
    body_md.append(
        "Next week's priorities will land tomorrow 8 AM. Rest easy tonight."
    )

    advice = {
        "report_type": "weekly_retrospective",
        "date": today.isoformat(),
        "generated_at": datetime.utcnow().isoformat() + "Z",
        "model": config.gemini_model or "n/a",
        "advice": "\n".join(body_md),
        "context_summary": {
            "oura_available": True,
            "lab_reports_count": 0,
            "lab_report_types": [],
            "image_analyses_count": 0,
            "image_severities": [],
        },
    }
    try:
        if config.email_to and config.smtp_host:
            send_advice_email(config, advice)
            print("Sent weekly retrospective email.")
    except Exception as exc:
        logger.warning(f"Retrospective email failed: {exc}")

    # WhatsApp one-line summary too
    try:
        from .whatsapp_sender import _run_openclaw_send

        head = f"📈 Week ending {today.isoformat()}: {totals['done']} action(s) done."
        if delta_lines:
            head += "\n" + delta_lines[0]
        if insight:
            head += "\n" + insight
        _run_openclaw_send(head)
    except Exception:
        pass
