"""Send daily health advice via email (SMTP)."""
from __future__ import annotations

import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict

from .config import SyncConfig


def send_advice_email(config: SyncConfig, advice: Dict[str, Any]) -> None:
    """Send the daily advice as an HTML email."""
    if not config.email_to:
        raise RuntimeError("EMAIL_TO is required to send advice by email")
    if not config.smtp_host:
        raise RuntimeError("SMTP_HOST is required to send advice by email")

    day = advice["date"]
    advice_text = advice["advice"]

    # Convert markdown-ish advice to simple HTML
    html_body = _markdown_to_html(advice_text)

    ctx = advice.get("context_summary", {})
    oura_badge = "Yes" if ctx.get("oura_available") else "No"
    lab_types = ", ".join(ctx.get("lab_report_types", [])) or "None"
    scan_count = ctx.get("image_analyses_count", 0)
    scan_info = f" &bull; Image scans: {scan_count}" if scan_count else ""

    html = f"""\
<html>
<head>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 640px; margin: 0 auto; padding: 20px; color: #1a1a1a; }}
  h2 {{ color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 8px; }}
  h3 {{ color: #1e40af; margin-top: 24px; }}
  .meta {{ font-size: 13px; color: #6b7280; margin-bottom: 24px; }}
  .footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb;
             font-size: 12px; color: #9ca3af; }}
</style>
</head>
<body>
  <h2>Daily Health Plan &mdash; {day}</h2>
  <div class="meta">
    Oura data: {oura_badge} &bull; Lab reports: {lab_types}{scan_info} &bull; Model: {advice.get('model', 'N/A')}
  </div>
  {html_body}
  <div class="footer">
    Generated by Personal Doctor &bull; {advice.get('generated_at', '')}
  </div>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Daily Health Plan — {day}"
    msg["From"] = config.smtp_user or f"health-advisor@{config.smtp_host}"
    msg["To"] = config.email_to

    # Plain-text fallback
    plain = (
        f"Daily Health Plan — {day}\n"
        f"Oura data: {oura_badge} | Lab reports: {lab_types}\n\n"
        f"{advice_text}\n\n"
        f"Generated: {advice.get('generated_at', '')}"
    )
    msg.attach(MIMEText(plain, "plain", "utf-8"))
    msg.attach(MIMEText(html, "html", "utf-8"))

    context = ssl.create_default_context()
    smtp_port = config.smtp_port or 465

    if smtp_port == 465:
        # SSL connection (Yahoo, etc.)
        with smtplib.SMTP_SSL(config.smtp_host, smtp_port, context=context) as server:
            if config.smtp_user and config.smtp_password:
                server.login(config.smtp_user, config.smtp_password)
            server.sendmail(msg["From"], [config.email_to], msg.as_string())
    else:
        # STARTTLS connection (Gmail on 587, etc.)
        with smtplib.SMTP(config.smtp_host, smtp_port) as server:
            server.ehlo()
            if smtp_port != 25:
                server.starttls(context=context)
                server.ehlo()
            if config.smtp_user and config.smtp_password:
                server.login(config.smtp_user, config.smtp_password)
            server.sendmail(msg["From"], [config.email_to], msg.as_string())


def _markdown_to_html(text: str) -> str:
    """Minimal markdown-to-HTML for the advice text."""
    import re

    lines = text.split("\n")
    html_lines = []
    in_list = False

    for line in lines:
        stripped = line.strip()

        if not stripped:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("<br>")
            continue

        # Headings
        if stripped.startswith("### "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h3>{stripped[4:]}</h3>")
            continue
        if stripped.startswith("## "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h2>{stripped[3:]}</h2>")
            continue

        # Bold
        stripped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", stripped)

        # Numbered list items
        if re.match(r"^\d+\.\s", stripped):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            content = re.sub(r"^\d+\.\s*", "", stripped)
            html_lines.append(f"<li>{content}</li>")
            continue

        # Bullet list items
        if stripped.startswith("- "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            html_lines.append(f"<li>{stripped[2:]}</li>")
            continue

        # Regular paragraph
        if in_list:
            html_lines.append("</ul>")
            in_list = False
        html_lines.append(f"<p>{stripped}</p>")

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)
